-- sso 0001: adopt_sso_providers
-- Generated by termix-plugin migrations. Review before committing.

CREATE TABLE IF NOT EXISTS `sso_providers` (
  `id` int AUTO_INCREMENT PRIMARY KEY,
  `name` text NOT NULL,
  `type` text NOT NULL,
  `enabled` boolean NOT NULL DEFAULT true,
  `display_order` int NOT NULL DEFAULT 0,
  `config` text NOT NULL,
  `created_at` text NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  `updated_at` text NOT NULL DEFAULT (CURRENT_TIMESTAMP)
);
RENAME TABLE `sso_providers` TO `p_sso_providers`;
