-- step-ca 0001: create_certs
-- Generated by termix-plugin migrations. Review before committing.

CREATE TABLE IF NOT EXISTS "p_step_ca_certs" (
  "id" serial PRIMARY KEY,
  "user_id" varchar(255) NOT NULL,
  "host_id" integer NOT NULL,
  "ssh_cert" text NOT NULL,
  "private_key" text NOT NULL,
  "email" text,
  "created_at" text NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "expires_at" varchar(255) NOT NULL,
  FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE,
  FOREIGN KEY ("host_id") REFERENCES "ssh_data" ("id") ON DELETE CASCADE
);
CREATE UNIQUE INDEX IF NOT EXISTS "idx_step_ca_certs_user_host" ON "p_step_ca_certs" ("user_id", "host_id");
