-- host-metrics 0001: adopt_host_metrics_tables
-- Generated by termix-plugin migrations. Review before committing.

CREATE TABLE IF NOT EXISTS `host_metrics_preferences` (
  `id` int AUTO_INCREMENT PRIMARY KEY,
  `user_id` varchar(255) NOT NULL,
  `host_id` int NOT NULL,
  `layout` text NOT NULL,
  `created_at` text NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  `updated_at` text NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE,
  FOREIGN KEY (`host_id`) REFERENCES `ssh_data` (`id`) ON DELETE CASCADE
);
RENAME TABLE `host_metrics_preferences` TO `p_host_metrics_host_metrics_preferences`;
CREATE TABLE IF NOT EXISTS `host_health_checks` (
  `id` int AUTO_INCREMENT PRIMARY KEY,
  `user_id` varchar(255) NOT NULL,
  `host_id` int NOT NULL,
  `checks` text NOT NULL,
  `interval_seconds` int NOT NULL DEFAULT 300,
  `created_at` text NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  `updated_at` text NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE,
  FOREIGN KEY (`host_id`) REFERENCES `ssh_data` (`id`) ON DELETE CASCADE
);
RENAME TABLE `host_health_checks` TO `p_host_metrics_host_health_checks`;
CREATE TABLE IF NOT EXISTS `host_health_history` (
  `id` int AUTO_INCREMENT PRIMARY KEY,
  `user_id` varchar(255) NOT NULL,
  `host_id` int NOT NULL,
  `check_id` varchar(255) NOT NULL,
  `ts` varchar(255) NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  `ok` boolean NOT NULL,
  `latency_ms` int,
  `detail` text,
  FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE,
  FOREIGN KEY (`host_id`) REFERENCES `ssh_data` (`id`) ON DELETE CASCADE
);
RENAME TABLE `host_health_history` TO `p_host_metrics_host_health_history`;
CREATE TABLE IF NOT EXISTS `host_metrics_history` (
  `id` int AUTO_INCREMENT PRIMARY KEY,
  `host_id` int NOT NULL,
  `ts` varchar(255) NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  `cpu_percent` double,
  `mem_percent` double,
  `disk_percent` double,
  `net_rx_bytes` int,
  `net_tx_bytes` int,
  FOREIGN KEY (`host_id`) REFERENCES `ssh_data` (`id`) ON DELETE CASCADE
);
RENAME TABLE `host_metrics_history` TO `p_host_metrics_host_metrics_history`;
