-- network-topology 0001: adopt_network_topology
-- Generated by termix-plugin migrations. Review before committing.

CREATE TABLE IF NOT EXISTS `network_topology` (
  `id` int AUTO_INCREMENT PRIMARY KEY,
  `user_id` varchar(255) NOT NULL,
  `topology` text,
  `created_at` text NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  `updated_at` text NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
);
RENAME TABLE `network_topology` TO `p_network_topology_graphs`;
