-- sso 0001: adopt_sso_providers
-- Generated by termix-plugin migrations. Review before committing.

CREATE TABLE IF NOT EXISTS "sso_providers" (
  "id" integer PRIMARY KEY AUTOINCREMENT,
  "name" text NOT NULL,
  "type" text NOT NULL,
  "enabled" integer NOT NULL DEFAULT 1,
  "display_order" integer NOT NULL DEFAULT 0,
  "config" text NOT NULL,
  "created_at" text NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" text NOT NULL DEFAULT CURRENT_TIMESTAMP
);
ALTER TABLE "sso_providers" RENAME TO "p_sso_providers";
