-- sso 0002: legacy_callback
-- Generated by termix-plugin migrations. Review before committing.

ALTER TABLE "p_sso_providers" ADD COLUMN "legacy_callback" integer NOT NULL DEFAULT 0;
-- Providers that existed before 2.9 were registered with the identity
-- provider under /users/oidc/callback, so they keep sending that URI.
UPDATE "p_sso_providers" SET "legacy_callback" = 1;
