-- session-recording 0001: adopt_session_recordings
-- Generated by termix-plugin migrations. Review before committing.

CREATE TABLE IF NOT EXISTS `session_recordings` (
  `id` int AUTO_INCREMENT PRIMARY KEY,
  `host_id` int NOT NULL,
  `user_id` varchar(255),
  `username` text,
  `access_id` int,
  `started_at` varchar(255) NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  `ended_at` text,
  `duration` int,
  `commands` text,
  `dangerous_actions` text,
  `recording_path` text,
  `protocol` text NOT NULL DEFAULT ('ssh'),
  `format` text NOT NULL DEFAULT ('text'),
  `terminated_by_owner` boolean DEFAULT false,
  `termination_reason` text,
  FOREIGN KEY (`host_id`) REFERENCES `ssh_data` (`id`) ON DELETE CASCADE
);
RENAME TABLE `session_recordings` TO `p_session_recording_session_recordings`;
