-- tmux-monitor 0001: adopt_tmux_session_tags
-- Generated by termix-plugin migrations. Review before committing.

CREATE TABLE IF NOT EXISTS "tmux_session_tags" (
  "id" serial PRIMARY KEY,
  "user_id" varchar(255) NOT NULL,
  "host_id" integer NOT NULL,
  "session_name" text NOT NULL,
  "tag" text NOT NULL,
  "created_at" text NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE,
  FOREIGN KEY ("host_id") REFERENCES "ssh_data" ("id") ON DELETE CASCADE
);
ALTER TABLE "tmux_session_tags" RENAME TO "p_tmux_monitor_session_tags";
