-- workspaces 0001: adopt_user_workspaces
-- Generated by termix-plugin migrations. Review before committing.

CREATE TABLE IF NOT EXISTS "user_workspaces" (
  "id" integer PRIMARY KEY AUTOINCREMENT,
  "user_id" text NOT NULL,
  "name" text NOT NULL,
  "color" text,
  "icon" text,
  "kind" text NOT NULL DEFAULT 'manual',
  "is_default" integer NOT NULL DEFAULT 0,
  "payload" text NOT NULL DEFAULT '{}',
  "sync_id" text UNIQUE,
  "created_at" text NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" text NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "last_used_at" text,
  FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS "idx_user_workspaces_user_id" ON "user_workspaces" ("user_id");
ALTER TABLE "user_workspaces" RENAME TO "p_workspaces_workspaces";
