-- totp 0001: create_enrollments
-- Generated by termix-plugin migrations. Review before committing.

CREATE TABLE IF NOT EXISTS `p_totp_enrollments` (
  `user_id` varchar(255) PRIMARY KEY NOT NULL,
  `secret` text,
  `pending_secret` text,
  `backup_codes` text,
  `created_at` text NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  `updated_at` text NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
);
