-- tunnels 0001: adopt_c2s_tunnel_presets
-- Generated by termix-plugin migrations. Review before committing.

CREATE TABLE IF NOT EXISTS "c2s_tunnel_presets" (
  "id" integer PRIMARY KEY AUTOINCREMENT,
  "user_id" text NOT NULL,
  "name" text NOT NULL,
  "config" text NOT NULL,
  "platform" text,
  "computer_name" text,
  "created_at" text NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" text NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE
);
ALTER TABLE "c2s_tunnel_presets" RENAME TO "p_tunnels_presets";
