-- session-recording 0001: adopt_session_recordings
-- Generated by termix-plugin migrations. Review before committing.

CREATE TABLE IF NOT EXISTS "session_recordings" (
  "id" serial PRIMARY KEY,
  "host_id" integer NOT NULL,
  "user_id" varchar(255),
  "username" text,
  "access_id" integer,
  "started_at" varchar(255) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "ended_at" text,
  "duration" integer,
  "commands" text,
  "dangerous_actions" text,
  "recording_path" text,
  "protocol" text NOT NULL DEFAULT 'ssh',
  "format" text NOT NULL DEFAULT 'text',
  "terminated_by_owner" boolean DEFAULT false,
  "termination_reason" text,
  FOREIGN KEY ("host_id") REFERENCES "ssh_data" ("id") ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS "idx_session_recordings_user_started" ON "session_recordings" ("user_id", "started_at");
CREATE INDEX IF NOT EXISTS "idx_session_recordings_host" ON "session_recordings" ("host_id");
ALTER TABLE "session_recordings" RENAME TO "p_session_recording_session_recordings";
