-- workspaces 0001: adopt_user_workspaces
-- Generated by termix-plugin migrations. Review before committing.

CREATE TABLE IF NOT EXISTS `user_workspaces` (
  `id` int AUTO_INCREMENT PRIMARY KEY,
  `user_id` varchar(255) NOT NULL,
  `name` text NOT NULL,
  `color` text,
  `icon` text,
  `kind` text NOT NULL DEFAULT ('manual'),
  `is_default` boolean NOT NULL DEFAULT false,
  `payload` text NOT NULL DEFAULT ('{}'),
  `sync_id` varchar(255) UNIQUE,
  `created_at` text NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  `updated_at` text NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  `last_used_at` text,
  FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
);
RENAME TABLE `user_workspaces` TO `p_workspaces_workspaces`;
