-- Termix 2.8.0 to 2.9.0 on mysql, generated by scripts/lib/upgrade-sql.mjs

-- ==== core 0024_thin_colleen_wing ====
CREATE TABLE `plugin_storage` (
	`id` int AUTO_INCREMENT NOT NULL,
	`plugin_id` varchar(255) NOT NULL,
	`key` varchar(255) NOT NULL,
	`value` text NOT NULL,
	`updated_at` varchar(255) NOT NULL DEFAULT (CURRENT_TIMESTAMP),
	CONSTRAINT `plugin_storage_id` PRIMARY KEY(`id`),
	CONSTRAINT `idx_plugin_storage_plugin_key` UNIQUE(`plugin_id`,`key`)
);
--> statement-breakpoint
ALTER TABLE `plugin_storage` ADD CONSTRAINT `plugin_storage_plugin_id_plugins_id_fk` FOREIGN KEY (`plugin_id`) REFERENCES `plugins`(`id`) ON DELETE cascade ON UPDATE no action;

-- ==== core 0025_wet_master_mold ====
DROP TABLE `alert_firings`;--> statement-breakpoint
DROP TABLE `alert_rule_channels`;--> statement-breakpoint
DROP TABLE `alert_rules`;

-- ==== core 0026_empty_black_bird ====
ALTER TABLE `plugin_permission_grants` MODIFY COLUMN `granted_by` varchar(255);--> statement-breakpoint
ALTER TABLE `plugin_permission_grants` ADD `source` text DEFAULT ('admin') NOT NULL;--> statement-breakpoint
ALTER TABLE `plugins` ADD `last_error` text;

-- ==== core 0027_watery_multiple_man ====
CREATE TABLE `plugin_migrations` (
	`id` int AUTO_INCREMENT NOT NULL,
	`plugin_id` varchar(255) NOT NULL,
	`migration_id` varchar(255) NOT NULL,
	`checksum` text NOT NULL,
	`applied_at` text NOT NULL DEFAULT (CURRENT_TIMESTAMP),
	CONSTRAINT `plugin_migrations_id` PRIMARY KEY(`id`),
	CONSTRAINT `idx_plugin_migrations_plugin_migration` UNIQUE(`plugin_id`,`migration_id`)
);
--> statement-breakpoint
ALTER TABLE `plugin_migrations` ADD CONSTRAINT `plugin_migrations_plugin_id_plugins_id_fk` FOREIGN KEY (`plugin_id`) REFERENCES `plugins`(`id`) ON DELETE cascade ON UPDATE no action;

-- ==== core 0028_fair_tusk ====
CREATE TABLE `rbac_applied_defaults` (
	`id` int AUTO_INCREMENT NOT NULL,
	`role_name` varchar(255) NOT NULL,
	`permission` varchar(255) NOT NULL,
	`applied_at` text NOT NULL DEFAULT (CURRENT_TIMESTAMP),
	CONSTRAINT `rbac_applied_defaults_id` PRIMARY KEY(`id`),
	CONSTRAINT `idx_rbac_applied_defaults_role_permission` UNIQUE(`role_name`,`permission`)
);
--> statement-breakpoint
CREATE TABLE `rbac_known_permissions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`permission` varchar(255) NOT NULL,
	`plugin_id` varchar(255),
	`first_seen_at` text NOT NULL DEFAULT (CURRENT_TIMESTAMP),
	CONSTRAINT `rbac_known_permissions_id` PRIMARY KEY(`id`),
	CONSTRAINT `idx_rbac_known_permissions_permission` UNIQUE(`permission`)
);

-- ==== core 0029_open_captain_america ====
CREATE TABLE `plugin_settings` (
	`id` int AUTO_INCREMENT NOT NULL,
	`plugin_id` varchar(255) NOT NULL,
	`scope` enum('admin','user','host','secret') NOT NULL,
	`scope_id` varchar(255),
	`key` varchar(255) NOT NULL,
	`value` text,
	`encrypted` boolean NOT NULL DEFAULT false,
	`updated_at` varchar(255) NOT NULL DEFAULT (CURRENT_TIMESTAMP),
	CONSTRAINT `plugin_settings_id` PRIMARY KEY(`id`),
	CONSTRAINT `idx_plugin_settings_scope_key` UNIQUE(`plugin_id`,`scope`,`scope_id`,`key`)
);
--> statement-breakpoint
ALTER TABLE `plugin_settings` ADD CONSTRAINT `plugin_settings_plugin_id_plugins_id_fk` FOREIGN KEY (`plugin_id`) REFERENCES `plugins`(`id`) ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX `idx_plugin_settings_plugin_scope` ON `plugin_settings` (`plugin_id`,`scope`);

-- ==== core 0030_sweet_warlock ====
CREATE TABLE `user_external_identities` (
	`id` int AUTO_INCREMENT NOT NULL,
	`user_id` varchar(255) NOT NULL,
	`provider_id` varchar(255) NOT NULL,
	`subject` varchar(255) NOT NULL,
	`email` text,
	`created_at` varchar(255) NOT NULL DEFAULT (CURRENT_TIMESTAMP),
	CONSTRAINT `user_external_identities_id` PRIMARY KEY(`id`),
	CONSTRAINT `idx_user_external_identities_provider_subject` UNIQUE(`provider_id`,`subject`)
);
--> statement-breakpoint
CREATE TABLE `user_second_factors` (
	`id` int AUTO_INCREMENT NOT NULL,
	`user_id` varchar(255) NOT NULL,
	`plugin_id` varchar(255) NOT NULL,
	`factor_id` varchar(255) NOT NULL,
	`enrolled_at` text NOT NULL DEFAULT (CURRENT_TIMESTAMP),
	CONSTRAINT `user_second_factors_id` PRIMARY KEY(`id`),
	CONSTRAINT `idx_user_second_factors_user_factor` UNIQUE(`user_id`,`plugin_id`,`factor_id`)
);
--> statement-breakpoint
ALTER TABLE `user_external_identities` ADD CONSTRAINT `user_external_identities_user_id_users_id_fk` FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `user_second_factors` ADD CONSTRAINT `user_second_factors_user_id_users_id_fk` FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX `idx_user_external_identities_user` ON `user_external_identities` (`user_id`);

-- ==== core 0031_nebulous_diamondback ====
-- user_workspaces moved to the workspaces plugin, whose first migration renames it
-- to p_workspaces_workspaces. Dropping it here would lose every saved workspace,
-- so this only stops drizzle tracking it. SELECT 1 because MySQL rejects an
-- empty query.
SELECT 1;

-- ==== core 0032_lethal_marrow ====
-- network_topology moved to the network-topology plugin, which adopts (renames)
-- this table in its own migration before this drizzle migration would run.
-- No DROP here: it would delete every row before the plugin's rename applies.
SELECT 1;

-- ==== core 0033_clear_anthem ====
-- snippets, snippet_folders and snippet_access moved to the snippets plugin
-- (p_snippets_*), adopted by rename rather than dropped. A real DROP TABLE
-- here would run before the plugin's adoption migration and delete every row.
SELECT 1;

-- ==== core 0034_green_vector ====
-- dropped, see plugin adoption (fleets plugin, migrations/mysql/0001_adopt_fleets.sql)
SELECT 1;

-- ==== core 0035_clumsy_leech ====
-- proxmox_node_history and proxmox_stats_preferences moved to the proxmox
-- plugin (p_proxmox_*), adopted by rename rather than dropped. The four
-- ssh_data proxmox columns are copied into the plugin's host settings after
-- plugins load, which is after this migration, so a real DROP COLUMN here
-- would delete the data first. The columns stay in place, unused, until 3.0.0.
SELECT 1;

-- ==== core 0036_dear_vapor ====
-- file_manager_pinned, file_manager_recent, file_manager_shortcuts and
-- transfer_recent are adopted (renamed, not dropped) by the file-manager
-- plugin's own migration, which runs at plugin activation, after core's
-- drizzle migrations. A DROP TABLE here would run first and delete the data.
SELECT 1;

-- ==== core 0037_foamy_norman_osborn ====
-- c2s_tunnel_presets moved to the tunnels plugin, whose first migration renames
-- it to p_tunnels_presets. Dropping it here would lose every saved preset, so
-- this only stops drizzle tracking it. SELECT 1 because MySQL rejects an
-- empty query.
SELECT 1;

-- ==== core 0038_quiet_karnak ====
-- command_history moved to the ssh-terminal plugin, whose first migration
-- renames it to p_ssh_terminal_command_history. Dropping it here would lose
-- every saved command, so this only stops drizzle tracking it. SELECT 1
-- because MySQL rejects an empty query.
SELECT 1;

-- ==== core 0039_condemned_shiva ====
-- tmux_session_tags moved to the tmux-monitor plugin, whose first migration
-- renames it to p_tmux_monitor_session_tags. Dropping it here would lose
-- every saved tag, so this only stops drizzle tracking it. SELECT 1 because
-- MySQL rejects an empty query.
SELECT 1;

-- ==== core 0040_misty_skin ====
-- session_shares, session_share_participants, collab_rooms and
-- collab_room_members moved to the session-sharing plugin, whose first
-- migration renames them. Dropping them here would lose every share and
-- room, so this only stops drizzle tracking them. SELECT 1 because MySQL
-- rejects an empty query.
SELECT 1;

-- ==== core 0041_wonderful_cargill ====
-- session_recordings moved to the session-recording plugin, whose first
-- migration renames it. Dropping it here would lose every recording, so
-- this only stops drizzle tracking it. SELECT 1 because MySQL rejects an
-- empty query.
SELECT 1;

-- ==== core 0042_colorful_bill_hollister ====
-- The remote desktop host options (enable_rdp, enable_vnc, enable_telnet,
-- the three ports, rdp_security, rdp_ignore_cert, security, ignore_cert,
-- guacamole_config) and user_preferences.rdp_defaults moved to the
-- remote-desktop plugin's settings. The copy runs after plugins load, which
-- is after this migration, so a real DROP COLUMN here would delete the data
-- first. The columns stay in place, unused, until 3.0.0.
SELECT 1;

-- ==== core 0043_unusual_lucky_pierre ====
-- host_metrics_preferences, host_health_checks, host_health_history and
-- host_metrics_history moved to the host-metrics plugin, which adopts them by
-- rename in its own first migration. That runs after this one, so a real
-- DROP TABLE here would delete every row first.
SELECT 1;--> statement-breakpoint
-- Status checks are core: the per-host switch and interval, copied out of
-- stats_config at boot by host-status-config-migration.ts.
ALTER TABLE `ssh_data` ADD `status_check_enabled` boolean DEFAULT true NOT NULL;--> statement-breakpoint
ALTER TABLE `ssh_data` ADD `status_check_interval` int;

-- ==== core 0044_jittery_thunderball ====
-- ssh_data.stats_config split: its status half moved to status_check_enabled
-- and status_check_interval, its metrics half to the host-metrics plugin's
-- host settings. Both copies run at boot, after this migration, so a real
-- DROP COLUMN here would delete the data first. The column stays in place,
-- unused, until 3.0.0.
SELECT 1;

-- ==== core 0045_flowery_the_hood ====
-- ssh_data.enable_docker and docker_config moved to the docker plugin's host
-- settings. The copy runs at boot, after this migration, so a real DROP
-- COLUMN here would delete the data first. The columns stay in place,
-- unused, until 3.0.0.
SELECT 1;

-- ==== core 0046_rich_logan ====
-- The automation tables moved to the automations plugin, which renames them
-- into its own namespace at activation. That runs after this migration, so a
-- real DROP TABLE here would delete every automation first.
SELECT 1;

-- ==== core 0047_red_silver_sable ====
-- The ai tables moved to the ai plugin, which renames them into its own
-- namespace at activation, and ssh_data.enable_ai_assistant and the two
-- user_preferences ai columns moved to its settings. Both run after this
-- migration, so a real DROP here would delete the data first. The columns
-- stay in place, unused, until 3.0.0. The timestamp and label type changes
-- drizzle-kit also wrote are generator drift (see FINISH-LIST.md), not a
-- change to the database, and are left out on purpose.
SELECT 1;

-- ==== core 0048_hard_demogoblin ====
-- dashboard_service_links, homepage_items and homepage_layouts moved to the
-- homepage plugin, which adopts them by rename at activation (see
-- plugins/homepage/migrations/mysql/0001_adopt_homepage_tables.sql).
-- Dropping them here would delete every row before the plugin's migration
-- ever runs, since this runs at boot before the plugins table exists.
SELECT 1;

-- ==== core 0049_quiet_blacklash ====
-- mac_address and wol_broadcast_address move to the wake-on-lan plugin's
-- host settings at boot, after this migration runs. Dropping them here would
-- delete the data before the copy has a chance to run.
SELECT 1;

-- ==== core 0050_optimal_speedball ====
-- secret_sources moves to the secret-sources plugin's adopted table at
-- activation, after this migration runs. Dropping it here would delete the
-- data before the plugin has a chance to rename it.
SELECT 1;

-- ==== core 0051_icy_hercules ====
-- webauthn_credentials moves to the webauthn plugin's adopted table at
-- activation, and the users TOTP columns are read by the TOTP boot migration
-- after this runs. Dropping either here would lose the data first.
SELECT 1;

-- ==== core 0052_illegal_gladiator ====
-- sso_providers moves to the sso plugin's adopted table at activation, and
-- its LDAP rows are copied into the ldap plugin by a boot migration after
-- this runs. Dropping it here would lose the data first.
SELECT 1;

-- ==== core 0053_magical_groot ====
-- opkssh_tokens moves to the opkssh plugin's adopted table at activation,
-- and ssh_data.use_warpgate is copied into the warpgate plugin's host
-- settings by a boot migration after this runs. Dropping either here would
-- lose the data first.
SELECT 1;

-- ==== core 0054_wakeful_misty_knight ====
-- vault_profiles and vault_tokens move to the vault plugin's adopted tables
-- at activation, and ssh_data.vault_profile_id is copied into the vault
-- plugin's host settings by a boot migration after this runs. Dropping any
-- of them here would lose the data first.
SELECT 1;

-- ==== core 0055_icy_patch ====
-- termix_identities, termix_identity_keys and termix_identity_ca move to the
-- termix-identity plugin's adopted tables at activation. Dropping them here
-- would lose the data first.
SELECT 1;

-- ==== core 0056_supreme_toad_men ====
-- The dialect generator now decides varchar or text per table. Columns that
-- were varchar(255) only because the same name was a key in another table
-- become text, and the timestamps and labels B18's regeneration left as
-- varchar(255) on real databases follow. varchar to text keeps every value.
ALTER TABLE `api_keys` MODIFY COLUMN `name` text NOT NULL;--> statement-breakpoint
ALTER TABLE `api_keys` MODIFY COLUMN `created_at` text NOT NULL DEFAULT (CURRENT_TIMESTAMP);--> statement-breakpoint
ALTER TABLE `api_keys` MODIFY COLUMN `expires_at` text;--> statement-breakpoint
ALTER TABLE `credential_access` MODIFY COLUMN `expires_at` text;--> statement-breakpoint
ALTER TABLE `credential_access` MODIFY COLUMN `created_at` text NOT NULL DEFAULT (CURRENT_TIMESTAMP);--> statement-breakpoint
ALTER TABLE `credential_sidebar_preferences` MODIFY COLUMN `updated_at` text NOT NULL DEFAULT (CURRENT_TIMESTAMP);--> statement-breakpoint
ALTER TABLE `folder_access` MODIFY COLUMN `expires_at` text;--> statement-breakpoint
ALTER TABLE `folder_access` MODIFY COLUMN `created_at` text NOT NULL DEFAULT (CURRENT_TIMESTAMP);--> statement-breakpoint
ALTER TABLE `host_access` MODIFY COLUMN `created_at` text NOT NULL DEFAULT (CURRENT_TIMESTAMP);--> statement-breakpoint
ALTER TABLE `host_sidebar_preferences` MODIFY COLUMN `updated_at` text NOT NULL DEFAULT (CURRENT_TIMESTAMP);--> statement-breakpoint
ALTER TABLE `ssh_data` MODIFY COLUMN `name` text;--> statement-breakpoint
ALTER TABLE `ssh_data` MODIFY COLUMN `folder` text;--> statement-breakpoint
ALTER TABLE `ssh_data` MODIFY COLUMN `created_at` text NOT NULL DEFAULT (CURRENT_TIMESTAMP);--> statement-breakpoint
ALTER TABLE `ssh_data` MODIFY COLUMN `updated_at` text NOT NULL DEFAULT (CURRENT_TIMESTAMP);--> statement-breakpoint
ALTER TABLE `notification_channels` MODIFY COLUMN `name` text NOT NULL;--> statement-breakpoint
ALTER TABLE `notification_channels` MODIFY COLUMN `created_at` text NOT NULL DEFAULT (CURRENT_TIMESTAMP);--> statement-breakpoint
ALTER TABLE `plugin_install_counts` MODIFY COLUMN `updated_at` text NOT NULL DEFAULT (CURRENT_TIMESTAMP);--> statement-breakpoint
ALTER TABLE `plugin_registries` MODIFY COLUMN `name` text NOT NULL;--> statement-breakpoint
ALTER TABLE `plugin_settings` MODIFY COLUMN `updated_at` text NOT NULL DEFAULT (CURRENT_TIMESTAMP);--> statement-breakpoint
ALTER TABLE `plugin_storage` MODIFY COLUMN `updated_at` text NOT NULL DEFAULT (CURRENT_TIMESTAMP);--> statement-breakpoint
ALTER TABLE `plugins` MODIFY COLUMN `name` text NOT NULL;--> statement-breakpoint
ALTER TABLE `plugins` MODIFY COLUMN `updated_at` text NOT NULL DEFAULT (CURRENT_TIMESTAMP);--> statement-breakpoint
ALTER TABLE `rbac_known_permissions` MODIFY COLUMN `plugin_id` text;--> statement-breakpoint
ALTER TABLE `roles` MODIFY COLUMN `created_at` text NOT NULL DEFAULT (CURRENT_TIMESTAMP);--> statement-breakpoint
ALTER TABLE `roles` MODIFY COLUMN `updated_at` text NOT NULL DEFAULT (CURRENT_TIMESTAMP);--> statement-breakpoint
ALTER TABLE `sessions` MODIFY COLUMN `created_at` text NOT NULL DEFAULT (CURRENT_TIMESTAMP);--> statement-breakpoint
ALTER TABLE `shared_credential_secrets` MODIFY COLUMN `created_at` text NOT NULL DEFAULT (CURRENT_TIMESTAMP);--> statement-breakpoint
ALTER TABLE `shared_credential_secrets` MODIFY COLUMN `updated_at` text NOT NULL DEFAULT (CURRENT_TIMESTAMP);--> statement-breakpoint
ALTER TABLE `shared_host_auth_overrides` MODIFY COLUMN `created_at` text NOT NULL DEFAULT (CURRENT_TIMESTAMP);--> statement-breakpoint
ALTER TABLE `shared_host_auth_overrides` MODIFY COLUMN `updated_at` text NOT NULL DEFAULT (CURRENT_TIMESTAMP);--> statement-breakpoint
ALTER TABLE `shared_host_secrets` MODIFY COLUMN `created_at` text NOT NULL DEFAULT (CURRENT_TIMESTAMP);--> statement-breakpoint
ALTER TABLE `shared_host_secrets` MODIFY COLUMN `updated_at` text NOT NULL DEFAULT (CURRENT_TIMESTAMP);--> statement-breakpoint
ALTER TABLE `ssh_credentials` MODIFY COLUMN `name` text NOT NULL;--> statement-breakpoint
ALTER TABLE `ssh_credentials` MODIFY COLUMN `folder` text;--> statement-breakpoint
ALTER TABLE `ssh_credentials` MODIFY COLUMN `created_at` text NOT NULL DEFAULT (CURRENT_TIMESTAMP);--> statement-breakpoint
ALTER TABLE `ssh_credentials` MODIFY COLUMN `updated_at` text NOT NULL DEFAULT (CURRENT_TIMESTAMP);--> statement-breakpoint
ALTER TABLE `ssh_folders` MODIFY COLUMN `name` text NOT NULL;--> statement-breakpoint
ALTER TABLE `ssh_folders` MODIFY COLUMN `created_at` text NOT NULL DEFAULT (CURRENT_TIMESTAMP);--> statement-breakpoint
ALTER TABLE `ssh_folders` MODIFY COLUMN `updated_at` text NOT NULL DEFAULT (CURRENT_TIMESTAMP);--> statement-breakpoint
ALTER TABLE `sync_tombstones` MODIFY COLUMN `sync_id` text NOT NULL;--> statement-breakpoint
ALTER TABLE `trusted_devices` MODIFY COLUMN `created_at` text NOT NULL DEFAULT (CURRENT_TIMESTAMP);--> statement-breakpoint
ALTER TABLE `trusted_devices` MODIFY COLUMN `expires_at` text NOT NULL;--> statement-breakpoint
ALTER TABLE `ui_preferences` MODIFY COLUMN `updated_at` text NOT NULL DEFAULT (CURRENT_TIMESTAMP);--> statement-breakpoint
ALTER TABLE `user_external_identities` MODIFY COLUMN `created_at` text NOT NULL DEFAULT (CURRENT_TIMESTAMP);--> statement-breakpoint
ALTER TABLE `user_open_tabs` MODIFY COLUMN `label` text NOT NULL;--> statement-breakpoint
ALTER TABLE `user_open_tabs` MODIFY COLUMN `created_at` text NOT NULL DEFAULT (CURRENT_TIMESTAMP);--> statement-breakpoint
ALTER TABLE `user_open_tabs` MODIFY COLUMN `updated_at` text NOT NULL DEFAULT (CURRENT_TIMESTAMP);--> statement-breakpoint
ALTER TABLE `user_preferences` MODIFY COLUMN `updated_at` text NOT NULL DEFAULT (CURRENT_TIMESTAMP);

-- ==== core 0057_serious_shatterstar ====
-- The file manager, tunnels, web endpoint, terminal, tmux monitor, session
-- sharing and session recording host columns, and the dead show_*_in_sidebar
-- columns, moved to their plugins' host settings. The copies run after
-- plugins load, which is after this migration, so a real DROP COLUMN here
-- would delete the data first. The columns stay in place, unused, until 3.0.0.
SELECT 1;

-- ==== core 0058_boring_avengers ====
-- dismissed_alerts and notification_channels moved to the alerts plugin. It
-- renames the first into its own namespace and copies the second at
-- activation, both after this migration, so a real DROP TABLE here would
-- delete them first. notification_channels stays in place, unused, until
-- 3.0.0.
SELECT 1;

-- ==== core 0059_military_purple_man ====
CREATE TABLE `sync_conflicts` (
	`id` int AUTO_INCREMENT NOT NULL,
	`user_id` varchar(255) NOT NULL,
	`entity_type` text NOT NULL,
	`sync_id` text NOT NULL,
	`local_row` text NOT NULL,
	`server_revision` int NOT NULL,
	`created_at` text NOT NULL DEFAULT (CURRENT_TIMESTAMP),
	CONSTRAINT `sync_conflicts_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `sync_link` (
	`id` int AUTO_INCREMENT NOT NULL,
	`user_id` varchar(255) NOT NULL,
	`server_url` text NOT NULL,
	`server_name` text,
	`server_version` text,
	`session_token` text,
	`custom_headers` text,
	`basic_auth` text,
	`allow_invalid_certificate` boolean NOT NULL DEFAULT false,
	`remote_user_id` text,
	`remote_username` text,
	`account` text,
	`scope` text,
	`known_types` text,
	`cursor` int NOT NULL DEFAULT 0,
	`status` text NOT NULL DEFAULT ('idle'),
	`last_error` text,
	`linked_at` text NOT NULL DEFAULT (CURRENT_TIMESTAMP),
	`last_sync_at` text,
	CONSTRAINT `sync_link_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `sync_records` (
	`id` int AUTO_INCREMENT NOT NULL,
	`user_id` varchar(255) NOT NULL,
	`entity_type` varchar(255) NOT NULL,
	`sync_id` varchar(255) NOT NULL,
	`revision` int NOT NULL DEFAULT 0,
	`seq` int NOT NULL DEFAULT 0,
	`hash` text,
	`deleted` boolean NOT NULL DEFAULT false,
	`error` text,
	`error_hash` text,
	`updated_at` text NOT NULL DEFAULT (CURRENT_TIMESTAMP),
	CONSTRAINT `sync_records_id` PRIMARY KEY(`id`),
	CONSTRAINT `idx_sync_records_user_entity_sync` UNIQUE(`user_id`,`entity_type`,`sync_id`)
);
--> statement-breakpoint
ALTER TABLE `ssh_data` ADD `local_only` boolean DEFAULT false NOT NULL;--> statement-breakpoint
ALTER TABLE `ssh_data` ADD `shared_source` text;--> statement-breakpoint
ALTER TABLE `ssh_credentials` ADD `shared_source` text;--> statement-breakpoint
ALTER TABLE `ssh_folders` ADD `local_only` boolean DEFAULT false NOT NULL;--> statement-breakpoint
ALTER TABLE `sync_conflicts` ADD CONSTRAINT `sync_conflicts_user_id_users_id_fk` FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `sync_link` ADD CONSTRAINT `sync_link_user_id_users_id_fk` FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `sync_records` ADD CONSTRAINT `sync_records_user_id_users_id_fk` FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX `idx_sync_conflicts_user` ON `sync_conflicts` (`user_id`);--> statement-breakpoint
CREATE INDEX `idx_sync_records_user_seq` ON `sync_records` (`user_id`,`seq`);

-- ==== core 0060_mean_gorgon ====
DROP TABLE `sync_tombstones`;

-- ==== core 0061_plugin_settings_scope_enum ====
ALTER TABLE `plugin_settings` MODIFY COLUMN `scope` enum('admin','user','host','secret') NOT NULL;

-- ==== core 0062_smooth_speed ====
ALTER TABLE `ssh_data` ADD `ssh_options` text;

-- ==== core 0063_needy_radioactive_man ====
-- The RDP, VNC and Telnet logins moved out of ssh_data into host_protocol_auth.
-- A boot migration copies them after this runs, so the old ssh_data columns
-- and their foreign keys stay in place, unused, until 3.0.0.
CREATE TABLE `host_protocol_auth` (
	`id` int AUTO_INCREMENT NOT NULL,
	`host_id` int NOT NULL,
	`user_id` varchar(255) NOT NULL,
	`protocol` varchar(255) NOT NULL,
	`auth_type` text NOT NULL DEFAULT ('direct'),
	`credential_id` int,
	`username` text,
	`password` text,
	`fields` text,
	`secret_fields` text,
	`created_at` text NOT NULL DEFAULT (CURRENT_TIMESTAMP),
	`updated_at` text NOT NULL DEFAULT (CURRENT_TIMESTAMP),
	CONSTRAINT `host_protocol_auth_id` PRIMARY KEY(`id`),
	CONSTRAINT `idx_host_protocol_auth_host_protocol` UNIQUE(`host_id`,`protocol`)
);
--> statement-breakpoint
ALTER TABLE `shared_host_secrets` ADD `encrypted_fields` text;--> statement-breakpoint
ALTER TABLE `host_protocol_auth` ADD CONSTRAINT `host_protocol_auth_host_id_ssh_data_id_fk` FOREIGN KEY (`host_id`) REFERENCES `ssh_data`(`id`) ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `host_protocol_auth` ADD CONSTRAINT `host_protocol_auth_user_id_users_id_fk` FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `host_protocol_auth` ADD CONSTRAINT `host_protocol_auth_credential_id_ssh_credentials_id_fk` FOREIGN KEY (`credential_id`) REFERENCES `ssh_credentials`(`id`) ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE INDEX `idx_host_protocol_auth_user` ON `host_protocol_auth` (`user_id`);--> statement-breakpoint
CREATE INDEX `idx_host_protocol_auth_credential` ON `host_protocol_auth` (`credential_id`);

-- ==== core 0064_flippant_killer_shrike ====
-- ssh_data.autostart_password, autostart_key and autostart_key_password held
-- copies of a host's login for 2.8's autostart endpoint, which nothing has read
-- since. They leave the schema but stay in place, unused, until 3.0.0, so no
-- install loses what it stored.
SELECT 1;

-- ==== core 0065_ambiguous_agent_zero ====
CREATE TABLE `host_defaults` (
	`id` int AUTO_INCREMENT NOT NULL,
	`level` enum('admin','user','folder') NOT NULL,
	`scope_key` varchar(255) NOT NULL,
	`user_id` varchar(255),
	`folder_id` int,
	`namespace` varchar(255) NOT NULL,
	`key` varchar(255) NOT NULL,
	`value` text,
	`updated_by` text,
	`updated_at` text NOT NULL DEFAULT (CURRENT_TIMESTAMP),
	CONSTRAINT `host_defaults_id` PRIMARY KEY(`id`),
	CONSTRAINT `idx_host_defaults_scope_key` UNIQUE(`scope_key`,`namespace`,`key`)
);
--> statement-breakpoint
ALTER TABLE `ssh_data` ADD `default_overrides` text;--> statement-breakpoint
ALTER TABLE `host_defaults` ADD CONSTRAINT `host_defaults_user_id_users_id_fk` FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `host_defaults` ADD CONSTRAINT `host_defaults_folder_id_ssh_folders_id_fk` FOREIGN KEY (`folder_id`) REFERENCES `ssh_folders`(`id`) ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX `idx_host_defaults_user` ON `host_defaults` (`user_id`);--> statement-breakpoint
CREATE INDEX `idx_host_defaults_folder` ON `host_defaults` (`folder_id`);

-- ==== plugin workspaces 0001_adopt_user_workspaces.sql ====
-- workspaces 0001: adopt_user_workspaces
-- Generated by termix-plugin migrations. Review before committing.

CREATE TABLE IF NOT EXISTS `user_workspaces` (
  `id` int AUTO_INCREMENT PRIMARY KEY,
  `user_id` varchar(255) NOT NULL,
  `name` text NOT NULL,
  `color` text,
  `icon` text,
  `kind` text NOT NULL DEFAULT ('manual'),
  `is_default` boolean NOT NULL DEFAULT false,
  `payload` text NOT NULL DEFAULT ('{}'),
  `sync_id` varchar(255) UNIQUE,
  `created_at` text NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  `updated_at` text NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  `last_used_at` text,
  FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
);
RENAME TABLE `user_workspaces` TO `p_workspaces_workspaces`;

-- ==== plugin network-topology 0001_adopt_network_topology.sql ====
-- network-topology 0001: adopt_network_topology
-- Generated by termix-plugin migrations. Review before committing.

CREATE TABLE IF NOT EXISTS `network_topology` (
  `id` int AUTO_INCREMENT PRIMARY KEY,
  `user_id` varchar(255) NOT NULL,
  `topology` text,
  `created_at` text NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  `updated_at` text NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
);
RENAME TABLE `network_topology` TO `p_network_topology_graphs`;

-- ==== plugin snippets 0001_adopt_snippets_tables.sql ====
-- snippets 0001: adopt_snippets_tables
-- Generated by termix-plugin migrations. Review before committing.

CREATE TABLE IF NOT EXISTS `snippets` (
  `id` int AUTO_INCREMENT PRIMARY KEY,
  `user_id` varchar(255) NOT NULL,
  `name` text NOT NULL,
  `content` text NOT NULL,
  `description` text,
  `folder` text,
  `order` int NOT NULL DEFAULT 0,
  `sync_id` varchar(255) UNIQUE,
  `created_at` text NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  `updated_at` text NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  `host_filter` text,
  `is_note` boolean NOT NULL DEFAULT false,
  FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
);
RENAME TABLE `snippets` TO `p_snippets_snippets`;
CREATE TABLE IF NOT EXISTS `snippet_folders` (
  `id` int AUTO_INCREMENT PRIMARY KEY,
  `user_id` varchar(255) NOT NULL,
  `name` text NOT NULL,
  `color` text,
  `icon` text,
  `sync_id` varchar(255) UNIQUE,
  `created_at` text NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  `updated_at` text NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
);
RENAME TABLE `snippet_folders` TO `p_snippets_snippet_folders`;
CREATE TABLE IF NOT EXISTS `snippet_access` (
  `id` int AUTO_INCREMENT PRIMARY KEY,
  `snippet_id` int NOT NULL,
  `user_id` varchar(255),
  `role_id` int,
  `granted_by` varchar(255) NOT NULL,
  `permission_level` text NOT NULL DEFAULT ('view'),
  `expires_at` text,
  `created_at` text NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  FOREIGN KEY (`granted_by`) REFERENCES `users` (`id`) ON DELETE CASCADE
);
RENAME TABLE `snippet_access` TO `p_snippets_snippet_access`;

-- ==== plugin fleets 0001_adopt_fleets.sql ====
-- fleets 0001: adopt_fleets
-- Generated by termix-plugin migrations. Review before committing.

CREATE TABLE IF NOT EXISTS `fleets` (
  `id` int AUTO_INCREMENT PRIMARY KEY,
  `user_id` varchar(255) NOT NULL,
  `name` text NOT NULL,
  `description` text,
  `color` text,
  `icon` text,
  `tag_rules` text,
  `sync_id` varchar(255) UNIQUE,
  `created_at` text NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  `updated_at` text NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
);
RENAME TABLE `fleets` TO `p_fleets_fleets`;
CREATE TABLE IF NOT EXISTS `fleet_members` (
  `id` int AUTO_INCREMENT PRIMARY KEY,
  `fleet_id` int NOT NULL,
  `host_id` int NOT NULL,
  `added_at` text NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  FOREIGN KEY (`fleet_id`) REFERENCES `p_fleets_fleets` (`id`) ON DELETE CASCADE,
  FOREIGN KEY (`host_id`) REFERENCES `ssh_data` (`id`) ON DELETE CASCADE
);
RENAME TABLE `fleet_members` TO `p_fleets_members`;
CREATE TABLE IF NOT EXISTS `fleet_inventory` (
  `id` int AUTO_INCREMENT PRIMARY KEY,
  `host_id` int NOT NULL,
  `user_id` varchar(255) NOT NULL,
  `os_pretty_name` text,
  `kernel` text,
  `architecture` text,
  `hostname` text,
  `uptime_seconds` int,
  `ip` text,
  `package_manager` text,
  `collected_at` text NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  FOREIGN KEY (`host_id`) REFERENCES `ssh_data` (`id`) ON DELETE CASCADE,
  FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
);
RENAME TABLE `fleet_inventory` TO `p_fleets_inventory`;

-- ==== plugin ssh-terminal 0001_adopt_command_history.sql ====
-- ssh-terminal 0001: adopt_command_history
-- Generated by termix-plugin migrations. Review before committing.

CREATE TABLE IF NOT EXISTS `command_history` (
  `id` int AUTO_INCREMENT PRIMARY KEY,
  `user_id` varchar(255) NOT NULL,
  `host_id` int NOT NULL,
  `command` text NOT NULL,
  `executed_at` text NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE,
  FOREIGN KEY (`host_id`) REFERENCES `ssh_data` (`id`) ON DELETE CASCADE
);
RENAME TABLE `command_history` TO `p_ssh_terminal_command_history`;

-- ==== plugin tunnels 0001_adopt_c2s_tunnel_presets.sql ====
-- tunnels 0001: adopt_c2s_tunnel_presets
-- Generated by termix-plugin migrations. Review before committing.

CREATE TABLE IF NOT EXISTS `c2s_tunnel_presets` (
  `id` int AUTO_INCREMENT PRIMARY KEY,
  `user_id` varchar(255) NOT NULL,
  `name` text NOT NULL,
  `config` text NOT NULL,
  `platform` text,
  `computer_name` text,
  `created_at` text NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  `updated_at` text NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
);
RENAME TABLE `c2s_tunnel_presets` TO `p_tunnels_presets`;

-- ==== plugin host-metrics 0001_adopt_host_metrics_tables.sql ====
-- host-metrics 0001: adopt_host_metrics_tables
-- Generated by termix-plugin migrations. Review before committing.

CREATE TABLE IF NOT EXISTS `host_metrics_preferences` (
  `id` int AUTO_INCREMENT PRIMARY KEY,
  `user_id` varchar(255) NOT NULL,
  `host_id` int NOT NULL,
  `layout` text NOT NULL,
  `created_at` text NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  `updated_at` text NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE,
  FOREIGN KEY (`host_id`) REFERENCES `ssh_data` (`id`) ON DELETE CASCADE
);
RENAME TABLE `host_metrics_preferences` TO `p_host_metrics_host_metrics_preferences`;
CREATE TABLE IF NOT EXISTS `host_health_checks` (
  `id` int AUTO_INCREMENT PRIMARY KEY,
  `user_id` varchar(255) NOT NULL,
  `host_id` int NOT NULL,
  `checks` text NOT NULL,
  `interval_seconds` int NOT NULL DEFAULT 300,
  `created_at` text NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  `updated_at` text NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE,
  FOREIGN KEY (`host_id`) REFERENCES `ssh_data` (`id`) ON DELETE CASCADE
);
RENAME TABLE `host_health_checks` TO `p_host_metrics_host_health_checks`;
CREATE TABLE IF NOT EXISTS `host_health_history` (
  `id` int AUTO_INCREMENT PRIMARY KEY,
  `user_id` varchar(255) NOT NULL,
  `host_id` int NOT NULL,
  `check_id` varchar(255) NOT NULL,
  `ts` varchar(255) NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  `ok` boolean NOT NULL,
  `latency_ms` int,
  `detail` text,
  FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE,
  FOREIGN KEY (`host_id`) REFERENCES `ssh_data` (`id`) ON DELETE CASCADE
);
RENAME TABLE `host_health_history` TO `p_host_metrics_host_health_history`;
CREATE TABLE IF NOT EXISTS `host_metrics_history` (
  `id` int AUTO_INCREMENT PRIMARY KEY,
  `host_id` int NOT NULL,
  `ts` varchar(255) NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  `cpu_percent` double,
  `mem_percent` double,
  `disk_percent` double,
  `net_rx_bytes` int,
  `net_tx_bytes` int,
  FOREIGN KEY (`host_id`) REFERENCES `ssh_data` (`id`) ON DELETE CASCADE
);
RENAME TABLE `host_metrics_history` TO `p_host_metrics_host_metrics_history`;

-- ==== plugin automations 0001_adopt_automations.sql ====
-- automations 0001: adopt_automations
-- Generated by termix-plugin migrations. Review before committing.
-- Hand-edited: keeps the legacy foreign keys the SDK cannot declare
-- (links between these tables, and a channel link to notification_channels).

CREATE TABLE IF NOT EXISTS `automations` (
  `id` int AUTO_INCREMENT PRIMARY KEY,
  `user_id` varchar(255) NOT NULL,
  `name` text NOT NULL,
  `description` text,
  `enabled` boolean NOT NULL DEFAULT true,
  `definition` text NOT NULL,
  `definition_version` int NOT NULL DEFAULT 1,
  `concurrency_policy` text NOT NULL DEFAULT ('skip'),
  `max_run_seconds` int NOT NULL DEFAULT 300,
  `dry_run` boolean NOT NULL DEFAULT false,
  `last_run_at` text,
  `last_run_status` text,
  `created_at` text NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  `updated_at` text NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
);
RENAME TABLE `automations` TO `p_automations_automations`;
CREATE TABLE IF NOT EXISTS `automation_trigger_state` (
  `id` int AUTO_INCREMENT PRIMARY KEY,
  `automation_id` int NOT NULL,
  `state_key` varchar(255) NOT NULL,
  `breach_started_at` text,
  `last_fired_at` text,
  `last_value` double,
  `last_observed_state` text,
  `updated_at` text NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  FOREIGN KEY (`automation_id`) REFERENCES `p_automations_automations` (`id`) ON DELETE CASCADE
);
RENAME TABLE `automation_trigger_state` TO `p_automations_trigger_state`;
CREATE TABLE IF NOT EXISTS `automation_schedules` (
  `id` int AUTO_INCREMENT PRIMARY KEY,
  `automation_id` int NOT NULL,
  `cron` text,
  `interval_seconds` int,
  `timezone` text,
  `next_due_at` varchar(255),
  `last_tick_at` text,
  FOREIGN KEY (`automation_id`) REFERENCES `p_automations_automations` (`id`) ON DELETE CASCADE
);
RENAME TABLE `automation_schedules` TO `p_automations_schedules`;
CREATE TABLE IF NOT EXISTS `automation_runs` (
  `id` int AUTO_INCREMENT PRIMARY KEY,
  `automation_id` int NOT NULL,
  `user_id` varchar(255) NOT NULL,
  `trigger_type` text NOT NULL,
  `trigger_context` text,
  `status` text NOT NULL,
  `started_at` varchar(255) NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  `finished_at` text,
  `duration_ms` int,
  `error` text,
  `dry_run` boolean NOT NULL DEFAULT false,
  `parent_run_id` int,
  FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE,
  FOREIGN KEY (`automation_id`) REFERENCES `p_automations_automations` (`id`) ON DELETE CASCADE
);
RENAME TABLE `automation_runs` TO `p_automations_runs`;
CREATE TABLE IF NOT EXISTS `automation_run_steps` (
  `id` int AUTO_INCREMENT PRIMARY KEY,
  `run_id` int NOT NULL,
  `step_index` int NOT NULL,
  `step_id` text NOT NULL,
  `step_type` text NOT NULL,
  `status` text NOT NULL,
  `started_at` text NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  `finished_at` text,
  `output` text,
  `error` text,
  `truncated` boolean NOT NULL DEFAULT false,
  FOREIGN KEY (`run_id`) REFERENCES `p_automations_runs` (`id`) ON DELETE CASCADE
);
RENAME TABLE `automation_run_steps` TO `p_automations_run_steps`;
CREATE TABLE IF NOT EXISTS `automation_channels` (
  `id` int AUTO_INCREMENT PRIMARY KEY,
  `automation_id` int NOT NULL,
  `channel_id` int NOT NULL,
  FOREIGN KEY (`automation_id`) REFERENCES `p_automations_automations` (`id`) ON DELETE CASCADE,
  FOREIGN KEY (`channel_id`) REFERENCES `notification_channels` (`id`) ON DELETE CASCADE
);
RENAME TABLE `automation_channels` TO `p_automations_channels`;

-- ==== plugin automations 0002_unlink_channels.sql ====
-- automations 0002: unlink_channels
-- Hand-written: channels moved from core's notification_channels to the
-- alerts plugin, so the link table drops its foreign key to the old table.
-- The constraint's name differs between installs, so the table is rebuilt.

CREATE TABLE IF NOT EXISTS `p_automations_channels_v2` (
  `id` int AUTO_INCREMENT PRIMARY KEY,
  `automation_id` int NOT NULL,
  `channel_id` int NOT NULL,
  FOREIGN KEY (`automation_id`) REFERENCES `p_automations_automations` (`id`) ON DELETE CASCADE
);
INSERT INTO `p_automations_channels_v2` (`id`, `automation_id`, `channel_id`) SELECT `id`, `automation_id`, `channel_id` FROM `p_automations_channels`;
DROP TABLE `p_automations_channels`;
RENAME TABLE `p_automations_channels_v2` TO `p_automations_channels`;
CREATE UNIQUE INDEX `idx_automation_channels_pair` ON `p_automations_channels` (`automation_id`, `channel_id`);

-- ==== plugin automations 0003_host_maintenance.sql ====
-- automations 0003: host_maintenance
-- Generated by termix-plugin migrations. Review before committing.

CREATE TABLE IF NOT EXISTS `p_automations_host_maintenance` (
  `id` int AUTO_INCREMENT PRIMARY KEY,
  `user_id` varchar(255) NOT NULL,
  `host_id` int NOT NULL,
  `state` text NOT NULL,
  FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE,
  FOREIGN KEY (`host_id`) REFERENCES `ssh_data` (`id`) ON DELETE CASCADE
);
CREATE UNIQUE INDEX `maintenance_host_owner` ON `p_automations_host_maintenance` (`user_id`, `host_id`);

-- ==== plugin automations 0004_rename_maintenance_index.sql ====
-- automations 0004: rename_maintenance_index
-- Renames the maintenance index to the idx_ pattern every other index uses.

CREATE UNIQUE INDEX `idx_automation_maintenance_host_owner` ON `p_automations_host_maintenance` (`user_id`, `host_id`);
DROP INDEX `maintenance_host_owner` ON `p_automations_host_maintenance`;

-- ==== plugin homepage 0001_adopt_homepage_tables.sql ====
-- homepage 0001: adopt_homepage_tables
-- Generated by termix-plugin migrations. Review before committing.

CREATE TABLE IF NOT EXISTS `homepage_items` (
  `id` int AUTO_INCREMENT PRIMARY KEY,
  `user_id` varchar(255) NOT NULL,
  `type_id` text NOT NULL,
  `title` text,
  `config` text NOT NULL DEFAULT ('{}'),
  `folder_id` int,
  `sync_id` varchar(255) UNIQUE,
  `created_at` text NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  `updated_at` text NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
);
RENAME TABLE `homepage_items` TO `p_homepage_homepage_items`;
CREATE TABLE IF NOT EXISTS `homepage_layouts` (
  `id` int AUTO_INCREMENT PRIMARY KEY,
  `user_id` varchar(255) NOT NULL UNIQUE,
  `layout` text NOT NULL DEFAULT ('{}'),
  `updated_at` text NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
);
RENAME TABLE `homepage_layouts` TO `p_homepage_homepage_layouts`;
CREATE TABLE IF NOT EXISTS `dashboard_service_links` (
  `id` int AUTO_INCREMENT PRIMARY KEY,
  `user_id` varchar(255) NOT NULL,
  `label` text NOT NULL,
  `url` text NOT NULL,
  `order` int NOT NULL DEFAULT 0,
  `sync_id` varchar(255) UNIQUE,
  `created_at` text NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  `updated_at` text NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
);
RENAME TABLE `dashboard_service_links` TO `p_homepage_dashboard_service_links`;

-- ==== plugin ai 0001_adopt_ai_tables.sql ====
-- ai 0001: adopt_ai_tables
-- Generated by termix-plugin migrations. Review before committing.
-- Hand-edited: keeps the legacy foreign key from messages and proposals to
-- their conversation, which the SDK cannot declare.

CREATE TABLE IF NOT EXISTS `ai_providers` (
  `id` int AUTO_INCREMENT PRIMARY KEY,
  `user_id` varchar(255) NOT NULL,
  `provider_type` text NOT NULL,
  `label` varchar(255) NOT NULL,
  `base_url` text,
  `api_key_prefix` text,
  `default_model` text,
  `enabled` boolean NOT NULL DEFAULT true,
  `created_at` text NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  `updated_at` text NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
);
RENAME TABLE `ai_providers` TO `p_ai_providers`;
CREATE TABLE IF NOT EXISTS `ai_conversations` (
  `id` int AUTO_INCREMENT PRIMARY KEY,
  `user_id` varchar(255) NOT NULL,
  `title` text,
  `provider_id` int,
  `model` text,
  `created_at` text NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  `updated_at` varchar(255) NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
);
RENAME TABLE `ai_conversations` TO `p_ai_conversations`;
CREATE TABLE IF NOT EXISTS `ai_messages` (
  `id` int AUTO_INCREMENT PRIMARY KEY,
  `conversation_id` int NOT NULL,
  `role` text NOT NULL,
  `content` text NOT NULL DEFAULT (''),
  `tool_calls` text,
  `created_at` varchar(255) NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  FOREIGN KEY (`conversation_id`) REFERENCES `p_ai_conversations` (`id`) ON DELETE CASCADE
);
RENAME TABLE `ai_messages` TO `p_ai_messages`;
CREATE TABLE IF NOT EXISTS `ai_proposals` (
  `id` int AUTO_INCREMENT PRIMARY KEY,
  `conversation_id` int NOT NULL,
  `user_id` varchar(255) NOT NULL,
  `kind` varchar(255) NOT NULL,
  `summary` text,
  `payload` text NOT NULL DEFAULT ('{}'),
  `status` varchar(32) NOT NULL DEFAULT 'pending',
  `applied_at` text,
  `result_summary` text,
  `created_at` text NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE,
  FOREIGN KEY (`conversation_id`) REFERENCES `p_ai_conversations` (`id`) ON DELETE CASCADE
);
RENAME TABLE `ai_proposals` TO `p_ai_proposals`;

-- ==== plugin ai 0002_provider_sync.sql ====
ALTER TABLE `p_ai_providers` ADD COLUMN `sync_id` varchar(255) UNIQUE;

-- ==== plugin alerts 0001_create_alerts.sql ====
-- alerts 0001: create_alerts
-- Generated by termix-plugin migrations. Review before committing.

CREATE TABLE IF NOT EXISTS `p_alerts_channels` (
  `id` int AUTO_INCREMENT PRIMARY KEY,
  `user_id` varchar(255) NOT NULL,
  `name` text NOT NULL,
  `type` varchar(32) NOT NULL,
  `config` text,
  `enabled` boolean NOT NULL DEFAULT true,
  `created_at` text NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  `updated_at` text NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
);
CREATE INDEX `idx_alerts_channels_user` ON `p_alerts_channels` (`user_id`);
CREATE TABLE IF NOT EXISTS `p_alerts_items` (
  `id` int AUTO_INCREMENT PRIMARY KEY,
  `user_id` varchar(255) NOT NULL,
  `source` varchar(64) NOT NULL,
  `category` varchar(128) NOT NULL,
  `severity` varchar(16) NOT NULL,
  `title` text NOT NULL,
  `body` text,
  `link` text,
  `context` text,
  `dedupe_key` varchar(255),
  `deliveries` text,
  `read_at` varchar(255),
  `created_at` varchar(255) NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
);
CREATE INDEX `idx_alerts_items_user` ON `p_alerts_items` (`user_id`, `created_at`);
CREATE INDEX `idx_alerts_items_unread` ON `p_alerts_items` (`user_id`, `read_at`);
CREATE INDEX `idx_alerts_items_dedupe` ON `p_alerts_items` (`user_id`, `dedupe_key`);
CREATE TABLE IF NOT EXISTS `p_alerts_rules` (
  `id` int AUTO_INCREMENT PRIMARY KEY,
  `user_id` varchar(255) NOT NULL,
  `name` text NOT NULL,
  `pattern` varchar(128) NOT NULL DEFAULT '*',
  `min_severity` varchar(16) NOT NULL DEFAULT 'warning',
  `channel_ids` text NOT NULL,
  `enabled` boolean NOT NULL DEFAULT true,
  `created_at` text NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
);
CREATE INDEX `idx_alerts_rules_user` ON `p_alerts_rules` (`user_id`);
CREATE TABLE IF NOT EXISTS `dismissed_alerts` (
  `id` int AUTO_INCREMENT PRIMARY KEY,
  `user_id` varchar(255) NOT NULL,
  `alert_id` text NOT NULL,
  `dismissed_at` text NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
);
RENAME TABLE `dismissed_alerts` TO `p_alerts_dismissed`;

-- ==== plugin file-manager 0001_adopt_file_manager_tables.sql ====
-- file-manager 0001: adopt_file_manager_tables
-- Generated by termix-plugin migrations. Review before committing.

CREATE TABLE IF NOT EXISTS `file_manager_recent` (
  `id` int AUTO_INCREMENT PRIMARY KEY,
  `user_id` varchar(255) NOT NULL,
  `host_id` int NOT NULL,
  `name` text NOT NULL,
  `path` text NOT NULL,
  `last_opened` text NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE,
  FOREIGN KEY (`host_id`) REFERENCES `ssh_data` (`id`) ON DELETE CASCADE
);
RENAME TABLE `file_manager_recent` TO `p_file_manager_recent`;
CREATE TABLE IF NOT EXISTS `file_manager_pinned` (
  `id` int AUTO_INCREMENT PRIMARY KEY,
  `user_id` varchar(255) NOT NULL,
  `host_id` int NOT NULL,
  `name` text NOT NULL,
  `path` text NOT NULL,
  `pinned_at` text NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE,
  FOREIGN KEY (`host_id`) REFERENCES `ssh_data` (`id`) ON DELETE CASCADE
);
RENAME TABLE `file_manager_pinned` TO `p_file_manager_pinned`;
CREATE TABLE IF NOT EXISTS `file_manager_shortcuts` (
  `id` int AUTO_INCREMENT PRIMARY KEY,
  `user_id` varchar(255) NOT NULL,
  `host_id` int NOT NULL,
  `name` text NOT NULL,
  `path` text NOT NULL,
  `created_at` text NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE,
  FOREIGN KEY (`host_id`) REFERENCES `ssh_data` (`id`) ON DELETE CASCADE
);
RENAME TABLE `file_manager_shortcuts` TO `p_file_manager_shortcuts`;
CREATE TABLE IF NOT EXISTS `transfer_recent` (
  `id` int AUTO_INCREMENT PRIMARY KEY,
  `user_id` varchar(255) NOT NULL,
  `source_host_id` int NOT NULL,
  `dest_host_id` int NOT NULL,
  `dest_path` text NOT NULL,
  `dest_path_label` text NOT NULL,
  `last_used` text NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE,
  FOREIGN KEY (`source_host_id`) REFERENCES `ssh_data` (`id`) ON DELETE CASCADE,
  FOREIGN KEY (`dest_host_id`) REFERENCES `ssh_data` (`id`) ON DELETE CASCADE
);
RENAME TABLE `transfer_recent` TO `p_file_manager_transfer_recent`;

-- ==== plugin ldap 0001_create_providers.sql ====
-- ldap 0001: create_providers
-- Generated by termix-plugin migrations. Review before committing.

CREATE TABLE IF NOT EXISTS `p_ldap_providers` (
  `id` int AUTO_INCREMENT PRIMARY KEY,
  `name` text NOT NULL,
  `enabled` boolean NOT NULL DEFAULT true,
  `display_order` int NOT NULL DEFAULT 0,
  `config` text NOT NULL,
  `created_at` text NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  `updated_at` text NOT NULL DEFAULT (CURRENT_TIMESTAMP)
);

-- ==== plugin opkssh 0001_adopt_opkssh_tokens.sql ====
-- opkssh 0001: adopt_opkssh_tokens
-- Generated by termix-plugin migrations. Review before committing.

CREATE TABLE IF NOT EXISTS `opkssh_tokens` (
  `id` int AUTO_INCREMENT PRIMARY KEY,
  `user_id` varchar(255) NOT NULL,
  `host_id` int NOT NULL,
  `ssh_cert` text NOT NULL,
  `private_key` text NOT NULL,
  `email` text,
  `sub` text,
  `issuer` text,
  `audience` text,
  `created_at` text NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  `expires_at` varchar(255) NOT NULL,
  `last_used` text,
  FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE,
  FOREIGN KEY (`host_id`) REFERENCES `ssh_data` (`id`) ON DELETE CASCADE
);
RENAME TABLE `opkssh_tokens` TO `p_opkssh_tokens`;

-- ==== plugin proxmox 0001_adopt_proxmox_stats.sql ====
-- proxmox 0001: adopt_proxmox_stats
-- Generated by termix-plugin migrations. Review before committing.

CREATE TABLE IF NOT EXISTS `proxmox_node_history` (
  `id` int AUTO_INCREMENT PRIMARY KEY,
  `host_id` int NOT NULL,
  `ts` text NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  `cpu_percent` double,
  `mem_percent` double,
  `disk_percent` double,
  `net_rx_bytes` int,
  `net_tx_bytes` int,
  FOREIGN KEY (`host_id`) REFERENCES `ssh_data` (`id`) ON DELETE CASCADE
);
RENAME TABLE `proxmox_node_history` TO `p_proxmox_node_history`;
CREATE TABLE IF NOT EXISTS `proxmox_stats_preferences` (
  `id` int AUTO_INCREMENT PRIMARY KEY,
  `user_id` varchar(255) NOT NULL,
  `host_id` int NOT NULL,
  `layout` text NOT NULL,
  `created_at` text NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  `updated_at` text NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE,
  FOREIGN KEY (`host_id`) REFERENCES `ssh_data` (`id`) ON DELETE CASCADE
);
RENAME TABLE `proxmox_stats_preferences` TO `p_proxmox_stats_preferences`;

-- ==== plugin session-recording 0001_adopt_session_recordings.sql ====
-- session-recording 0001: adopt_session_recordings
-- Generated by termix-plugin migrations. Review before committing.

CREATE TABLE IF NOT EXISTS `session_recordings` (
  `id` int AUTO_INCREMENT PRIMARY KEY,
  `host_id` int NOT NULL,
  `user_id` varchar(255),
  `username` text,
  `access_id` int,
  `started_at` varchar(255) NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  `ended_at` text,
  `duration` int,
  `commands` text,
  `dangerous_actions` text,
  `recording_path` text,
  `protocol` text NOT NULL DEFAULT ('ssh'),
  `format` text NOT NULL DEFAULT ('text'),
  `terminated_by_owner` boolean DEFAULT false,
  `termination_reason` text,
  FOREIGN KEY (`host_id`) REFERENCES `ssh_data` (`id`) ON DELETE CASCADE
);
RENAME TABLE `session_recordings` TO `p_session_recording_session_recordings`;

-- ==== plugin secret-sources 0001_adopt_secret_sources.sql ====
-- secret-sources 0001: adopt_secret_sources
-- Generated by termix-plugin migrations. Review before committing.

CREATE TABLE IF NOT EXISTS `secret_sources` (
  `id` varchar(255) PRIMARY KEY NOT NULL,
  `user_id` varchar(255) NOT NULL,
  `name` text NOT NULL,
  `kind` text NOT NULL DEFAULT ('onepassword-connect'),
  `base_url` text NOT NULL,
  `shared` boolean NOT NULL DEFAULT false,
  `created_at` text NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  `updated_at` text NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
);
RENAME TABLE `secret_sources` TO `p_secret_sources_sources`;

-- ==== plugin session-sharing 0001_adopt_session_sharing.sql ====
-- session-sharing 0001: adopt_session_sharing
-- Generated by termix-plugin migrations. Review before committing.
-- Hand-edited: keeps the legacy foreign keys the SDK cannot declare
-- (nullable or set-null user and host links, and links between these tables).

CREATE TABLE IF NOT EXISTS `session_shares` (
  `id` varchar(255) PRIMARY KEY NOT NULL,
  `host_id` int NOT NULL,
  `owner_user_id` varchar(255) NOT NULL,
  `protocol` text NOT NULL,
  `session_id` varchar(255) NOT NULL,
  `tab_instance_id` text,
  `share_type` text NOT NULL,
  `target_user_id` varchar(255),
  `link_token` varchar(255) UNIQUE,
  `permission_level` text NOT NULL DEFAULT ('read-only'),
  `created_at` text NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  `expires_at` text NOT NULL,
  `revoked_at` text,
  `last_joined_at` text,
  `join_count` int NOT NULL DEFAULT 0,
  FOREIGN KEY (`host_id`) REFERENCES `ssh_data` (`id`) ON DELETE CASCADE,
  FOREIGN KEY (`owner_user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE,
  FOREIGN KEY (`target_user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
);
RENAME TABLE `session_shares` TO `p_session_sharing_shares`;
CREATE TABLE IF NOT EXISTS `session_share_participants` (
  `id` int AUTO_INCREMENT PRIMARY KEY,
  `share_id` varchar(255) NOT NULL,
  `user_id` varchar(255),
  `guest_label` text,
  `joined_at` text NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  `left_at` text,
  FOREIGN KEY (`share_id`) REFERENCES `p_session_sharing_shares` (`id`) ON DELETE CASCADE,
  FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
);
RENAME TABLE `session_share_participants` TO `p_session_sharing_share_participants`;
CREATE TABLE IF NOT EXISTS `collab_rooms` (
  `id` varchar(255) PRIMARY KEY NOT NULL,
  `name` text NOT NULL,
  `owner_user_id` varchar(255) NOT NULL,
  `persistent` boolean NOT NULL DEFAULT false,
  `presenter_user_id` varchar(255),
  `stage_protocol` text,
  `stage_host_id` int,
  `stage_share_id` varchar(255),
  `guest_link_token` varchar(255),
  `created_at` text NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  `ended_at` text,
  FOREIGN KEY (`owner_user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE,
  FOREIGN KEY (`presenter_user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  FOREIGN KEY (`stage_host_id`) REFERENCES `ssh_data` (`id`) ON DELETE SET NULL,
  FOREIGN KEY (`stage_share_id`) REFERENCES `p_session_sharing_shares` (`id`) ON DELETE SET NULL
);
RENAME TABLE `collab_rooms` TO `p_session_sharing_rooms`;
CREATE TABLE IF NOT EXISTS `collab_room_members` (
  `id` int AUTO_INCREMENT PRIMARY KEY,
  `room_id` varchar(255) NOT NULL,
  `user_id` varchar(255) NOT NULL,
  `room_role` text NOT NULL DEFAULT ('member'),
  `added_by` varchar(255),
  `created_at` text NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE,
  FOREIGN KEY (`room_id`) REFERENCES `p_session_sharing_rooms` (`id`) ON DELETE CASCADE,
  FOREIGN KEY (`added_by`) REFERENCES `users` (`id`) ON DELETE SET NULL
);
RENAME TABLE `collab_room_members` TO `p_session_sharing_room_members`;

-- ==== plugin sso 0001_adopt_sso_providers.sql ====
-- sso 0001: adopt_sso_providers
-- Generated by termix-plugin migrations. Review before committing.

CREATE TABLE IF NOT EXISTS `sso_providers` (
  `id` int AUTO_INCREMENT PRIMARY KEY,
  `name` text NOT NULL,
  `type` text NOT NULL,
  `enabled` boolean NOT NULL DEFAULT true,
  `display_order` int NOT NULL DEFAULT 0,
  `config` text NOT NULL,
  `created_at` text NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  `updated_at` text NOT NULL DEFAULT (CURRENT_TIMESTAMP)
);
RENAME TABLE `sso_providers` TO `p_sso_providers`;

-- ==== plugin sso 0002_legacy_callback.sql ====
-- sso 0002: legacy_callback
-- Generated by termix-plugin migrations. Review before committing.

ALTER TABLE `p_sso_providers` ADD COLUMN `legacy_callback` boolean NOT NULL DEFAULT false;
-- Providers that existed before 2.9 were registered with the identity
-- provider under /users/oidc/callback, so they keep sending that URI.
UPDATE `p_sso_providers` SET `legacy_callback` = true;

-- ==== plugin step-ca 0001_create_certs.sql ====
-- step-ca 0001: create_certs
-- Generated by termix-plugin migrations. Review before committing.

CREATE TABLE IF NOT EXISTS `p_step_ca_certs` (
  `id` int AUTO_INCREMENT PRIMARY KEY,
  `user_id` varchar(255) NOT NULL,
  `host_id` int NOT NULL,
  `ssh_cert` text NOT NULL,
  `private_key` text NOT NULL,
  `email` text,
  `created_at` text NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  `expires_at` varchar(255) NOT NULL,
  FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE,
  FOREIGN KEY (`host_id`) REFERENCES `ssh_data` (`id`) ON DELETE CASCADE
);
CREATE UNIQUE INDEX `idx_step_ca_certs_user_host` ON `p_step_ca_certs` (`user_id`, `host_id`);

-- ==== plugin termix-identity 0001_adopt_termix_identity_tables.sql ====
-- termix-identity 0001: adopt_termix_identity_tables
-- Generated by termix-plugin migrations. Review before committing.
-- Hand-edited: keeps the legacy foreign keys the SDK cannot declare
-- (keys and ca to their identity, keys to ssh_credentials).

CREATE TABLE IF NOT EXISTS `termix_identities` (
  `id` int AUTO_INCREMENT PRIMARY KEY,
  `user_id` varchar(255) NOT NULL UNIQUE,
  `handle` varchar(255) NOT NULL UNIQUE,
  `description` text,
  `created_at` text NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  `updated_at` text NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
);
RENAME TABLE `termix_identities` TO `p_termix_identity_identities`;
CREATE TABLE IF NOT EXISTS `termix_identity_keys` (
  `id` int AUTO_INCREMENT PRIMARY KEY,
  `identity_id` int NOT NULL,
  `user_id` varchar(255) NOT NULL,
  `public_key` text NOT NULL,
  `key_type` text NOT NULL,
  `algorithm` text NOT NULL,
  `label` text,
  `comment` text,
  `source` text NOT NULL DEFAULT ('manual'),
  `credential_id` int,
  `enabled` boolean NOT NULL DEFAULT true,
  `created_at` text NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE,
  FOREIGN KEY (`identity_id`) REFERENCES `p_termix_identity_identities` (`id`) ON DELETE CASCADE,
  FOREIGN KEY (`credential_id`) REFERENCES `ssh_credentials` (`id`) ON DELETE SET NULL
);
RENAME TABLE `termix_identity_keys` TO `p_termix_identity_keys`;
CREATE TABLE IF NOT EXISTS `termix_identity_ca` (
  `id` int AUTO_INCREMENT PRIMARY KEY,
  `identity_id` int NOT NULL UNIQUE,
  `user_id` varchar(255) NOT NULL,
  `public_key` text NOT NULL,
  `private_key` text NOT NULL,
  `validity_days` int NOT NULL DEFAULT 90,
  `created_at` text NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  `updated_at` text NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE,
  FOREIGN KEY (`identity_id`) REFERENCES `p_termix_identity_identities` (`id`) ON DELETE CASCADE
);
RENAME TABLE `termix_identity_ca` TO `p_termix_identity_ca`;

-- ==== plugin tmux-monitor 0001_adopt_tmux_session_tags.sql ====
-- tmux-monitor 0001: adopt_tmux_session_tags
-- Generated by termix-plugin migrations. Review before committing.

CREATE TABLE IF NOT EXISTS `tmux_session_tags` (
  `id` int AUTO_INCREMENT PRIMARY KEY,
  `user_id` varchar(255) NOT NULL,
  `host_id` int NOT NULL,
  `session_name` text NOT NULL,
  `tag` text NOT NULL,
  `created_at` text NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE,
  FOREIGN KEY (`host_id`) REFERENCES `ssh_data` (`id`) ON DELETE CASCADE
);
RENAME TABLE `tmux_session_tags` TO `p_tmux_monitor_session_tags`;

-- ==== plugin totp 0001_create_enrollments.sql ====
-- totp 0001: create_enrollments
-- Generated by termix-plugin migrations. Review before committing.

CREATE TABLE IF NOT EXISTS `p_totp_enrollments` (
  `user_id` varchar(255) PRIMARY KEY NOT NULL,
  `secret` text,
  `pending_secret` text,
  `backup_codes` text,
  `created_at` text NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  `updated_at` text NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
);

-- ==== plugin vault 0001_adopt_vault_tables.sql ====
-- vault 0001: adopt_vault_tables
-- Generated by termix-plugin migrations. Review before committing.

CREATE TABLE IF NOT EXISTS `vault_profiles` (
  `id` int AUTO_INCREMENT PRIMARY KEY,
  `user_id` varchar(255) NOT NULL,
  `name` text NOT NULL,
  `description` text,
  `folder` text,
  `tags` text,
  `vault_addr` text NOT NULL,
  `vault_namespace` text,
  `oidc_mount` text,
  `oidc_role` text,
  `ssh_mount` text,
  `ssh_role` text NOT NULL,
  `valid_principals` text,
  `key_type` text,
  `shared` boolean NOT NULL DEFAULT false,
  `sync_id` varchar(255) UNIQUE,
  `created_at` text NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  `updated_at` text NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
);
RENAME TABLE `vault_profiles` TO `p_vault_profiles`;
CREATE TABLE IF NOT EXISTS `vault_tokens` (
  `id` int AUTO_INCREMENT PRIMARY KEY,
  `user_id` varchar(255) NOT NULL,
  `profile_id` int NOT NULL,
  `ssh_cert` text NOT NULL,
  `private_key` text NOT NULL,
  `created_at` text NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  `expires_at` varchar(255) NOT NULL,
  `last_used` text,
  FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
);
RENAME TABLE `vault_tokens` TO `p_vault_tokens`;

-- ==== plugin webauthn 0001_adopt_webauthn_credentials.sql ====
-- webauthn 0001: adopt_webauthn_credentials
-- Generated by termix-plugin migrations. Review before committing.

CREATE TABLE IF NOT EXISTS `webauthn_credentials` (
  `id` varchar(255) PRIMARY KEY NOT NULL,
  `user_id` varchar(255) NOT NULL,
  `name` text NOT NULL,
  `credential_id` varchar(255) NOT NULL UNIQUE,
  `public_key` text NOT NULL,
  `counter` int NOT NULL DEFAULT 0,
  `device_type` text,
  `backed_up` boolean NOT NULL DEFAULT false,
  `transports` text,
  `user_verification` text NOT NULL DEFAULT ('preferred'),
  `created_at` text NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  `last_used_at` text,
  FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
);
RENAME TABLE `webauthn_credentials` TO `p_webauthn_credentials`;
